export const eSport = [
	{
		gameName: 'League of Legends',
		gameIcon: '/assets/league.png',
		endedTime: '4:32:40',
		teamA: 'Team Cocut',
		teamAIcon: '/assets/cocut.png',
		teamAScore: 3.4,
		teamB: 'Team Arrow',
		teamBIcon: '/assets/team-arrow.png',
		teamBScore: 2.35,
		isStake: false,
	},
	{
		gameName: 'Counter-Strike',
		gameIcon: '/assets/strike.png',
		endedTime: '2:32:34',
		teamA: 'Team Cutcat',
		teamAIcon: '/assets/cutcat.png',
		teamAScore: 1.43,
		teamB: 'Team Bounce',
		teamBIcon: '/assets/team-bounce.png',
		teamBScore: 3.22,
		isStake: false,
	},
	{
		gameName: 'Minecraft',
		gameIcon: '/assets/mine-crafe.png',
		endedTime: '3:45:12',
		teamA: 'Team ColdA',
		teamAIcon: '/assets/cold.png',
		teamAScore: 4.13,
		teamB: 'Team Gold',
		teamBIcon: '/assets/gold.png',
		teamBScore: 3.09,
		isStake: false,
	},
	{
		gameName: 'Rocket League',
		gameIcon: '/assets/rocket.png',
		endedTime: '2:22:45',
		teamA: 'Team Quick',
		teamAIcon: '/assets/quick.png',
		teamAScore: 2.19,
		teamB: 'Team Arrow',
		teamBIcon: '/assets/team-arrow.png',
		teamBScore: 3.67,
		isStake: false,
	},
	{
		gameName: 'FIFA',
		gameIcon: '/assets/fifa.png',
		endedTime: '5:34:23',
		teamA: 'Team Scout',
		teamAIcon: '/assets/scout.png',
		teamAScore: 3.54,
		teamB: 'Team Global',
		teamBIcon: '/assets/global.png',
		teamBScore: 2.26,
		isStake: false,
	},
	{
		gameName: 'Call of Duty',
		gameIcon: '/assets/duty.png',
		endedTime: '7:43:45',
		teamA: 'Team cocut',
		teamAIcon: '/assets/cocut.png',
		teamAScore: 5.61,
		teamB: 'Team Rex',
		teamBIcon: '/assets/rex.png',
		teamBScore: 3.52,
		isStake: false,
	},
];
